\c party_up;

INSERT INTO gamers (gamertag, pronouns, tagline, game, rank, role, age, image, country, about, socialmediaone, socialmediatwo, socialmediathree, status) VALUES
('YouthfulBanshee', 'she/her', '~Chill vibes~', 'Valorant', 'Diamond 3', 'Duelist', 21, 'https://media.istockphoto.com/photos/portrait-of-the-beautiful-young-pro-gamer-girl-sitting-at-her-and-picture-id1010651662?k=20&m=1010651662&s=612x612&w=0&h=AjFay4i7CmnUIQha1GNEkXu6WFuxnegGCanZZtJXbjY=', 'United States', 'My name is Julie and I''m looking to make new friends who play val! If you''re looking for a duelist main to carry you, I''m your girl.', 'Instagram', 'Facebook', 'Twitter', true),
('VultureNapa', 'he/him', 'Let''s hang out!', 'League of Legends', 'Gold 2', 'Jungle', 24, 'https://media.istockphoto.com/photos/focused-guy-in-a-yellow-cap-with-a-headset-is-playing-a-video-shooter-picture-id1369525226?b=1&k=20&m=1369525226&s=170667a&w=0&h=uvj0C6RIAYpqqvQhZ7l5clZnhS_sIOS-3orkWUsTIYg=', 'United Kingdom', 'Hey there, I''m Jared! I play league in amateur tournaments, so I love League! I''m looking for a partner who can grind some ranked with me. Let''s hit the rift!', 'Twitter', 'Instagram', 'YouTube', true),
('LavishLee', 'they/them', 'Teach meee :_)', 'Fortnite', 'Unranked', '',  20, 'https://media.istockphoto.com/photos/professional-esport-gamer-girl-live-streaming-and-plays-online-video-picture-id1248487887?k=20&m=1248487887&s=170667a&w=0&h=f1xEA2ujr3Cjwl4bIpTD-xIczihPtXWp3cagAZzlmcE=', 'Canada', 'Nice to meet you~ I''m new to Fortnite and I would love a duo to mentor me and have some fun games!', 'Tumblr', 'Instagram', 'Facebook', true),
('ThinCherries', 'she/her', 'Send me a meme <3', 'League of Legends', 'Silver 4', 'Mid',  22, 'https://appdevelopermagazine.com/multimedia/Professional-Gamer-Girl-Playing-in-First-Person-Shooter-Online-Video-Game-App-Developer-Magazine_ente62zq.jpg', 'United States', 'Hi there!!~ I play a lot of league of legos, and I would really love to meet someone who can play with me on the weekends! I''m super friendly so please dm me!!', 'Tumblr', 'Twitter', 'Reddit', true),
('HeavyHandsome', 'he/him', 'What''s Poppin', 'Valorant', 'Immortal 2', 'Duelist',  21, 'https://p.favim.com/orig/2019/01/08/red-light-red-lights-actor-Favim.com-6757280.jpg', 'United States', 'Yo what''s up, my name''s Dylan. I''m a Jett main, looking for my pocket Sage. Let''s kick it together', 'Twitter', 'Reddit', 'Instagram', false),
('FrozenKisse', 'she/her', 'A girl who loves long walks on the beach :)', 'Animal Crossing', 'Unranked', 'None',  22, 'https://img.freepik.com/free-photo/dreamy-young-woman-sunglasses-looking-front_197531-16739.jpg?w=360', 'Canada', 'Hiii I''m Aaliyah! I like to play games like Animal Crossing and Stardew Valley, and I''m looking for someone who will have a beach date with me in my animal crossing town :) ', 'Tumblr', 'Instagram', 'Facebook', false),
('EagerSpace', 'he/him', 'Party Up with me I make good pasta :D', 'Overwatch', 'Unranked', 'None',  25, 'https://www.machovibes.com/wp-content/uploads/2020/11/Selfie-Poses-For-Guys.jpg', 'United States', 'Hey hey nice to meet you! I''m a tank main in Overwatch, and I wanna meet some people who can play with me on weekends.', 'Reddit', 'Instagram', 'Facebook', false),
('GrimWhale', 'he/him', 'I like music, movies, and of course gaming. Hit me up!', 'Fortnite', 'Unranked', 'None',  26, 'https://images.unsplash.com/photo-1611651978410-7337973d675f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2VsZmllJTIwbWFufGVufDB8fDB8fA%3D%3D&w=1000&q=80', 'United States', 'Hello! I''m a Fortnite gamer. Not super great at building but I like to play nonetheless. When I''m not gaming, I like to go on long hikes, and I ride my bicycle everywhere', 'Reddit', 'Instagram', 'Facebook', true),
('SirenSong', 'she/her', 'Hiya~ I suck at val but maybe we can have some fun!', 'Valorant', 'Unranked', 'Sentinel',  26, 'https://media.istockphoto.com/photos/adult-african-american-sporty-woman-training-at-home-picture-id1281659594?k=20&m=1281659594&s=612x612&w=0&h=LESF-EcEvZCh4wFxcciYAas6OOw5fISLkxIENWyepOY=', 'United States', 'Hi! I''m Valerie, and I live in the US but was born in the UK. I love being active! I''m always at the gym or jogging in the park. I also really want to find frendly val player to duo with.', 'Reddit', 'Instagram', 'Facebook', true);
